# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: black-diff
        name: black-diff
        entry: poetry run black
        language: system
        types_or:
          - python
          - pyi
        require_serial: true
        args:
          - "--diff"
          - "--color"
        verbose: true
      - id: black
        name: black
        entry: poetry run black
        language: system
        types_or:
          - python
          - pyi
        require_serial: true
      - id: autoflake-diff
        name: autoflake-diff
        entry: poetry run autoflake
        language: system
        types:
          - python
        require_serial: true
        verbose: true
      - id: autoflake
        name: autoflake
        entry: poetry run autoflake
        language: system
        types:
          - python
        require_serial: true
        args:
          - "--in-place"
      - id: isort-diff
        name: isort-diff
        entry: poetry run isort
        language: system
        types:
          - python
        require_serial: true
        args:
          - "--diff"
          - "--color"
          - "--filter-files"
        verbose: true
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types:
          - python
        require_serial: true
        args:
          - "--filter-files"
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types:
          - python
        require_serial: true
      - id: bandit
        name: bandit
        entry: poetry run bandit
        language: system
        types:
          - python
        args:
          - "-c"
          - "pyproject.toml"
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types_or:
          - python
          - pyi
        require_serial: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: '^\.github/workflows/'
      - id: end-of-file-fixer
        exclude: '^\.github/workflows/'
      - id: check-yaml
      - id: check-added-large-files
